# Copyright (c) 2017 ~ 2025, the original author springcloudgateway individual Inc,
# All rights reserved. Contact us<springcloudgateway@163.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# #### SpringCloud gateway nacos configuration. ####
#
spring:
  cloud:
    nacos:
      config:
        enabled: true
        serverAddr: 127.0.0.1:8848
        #username:
        #password:
        fileExtension: yml
        name: ${spring.application.name}-route
        group: DEFAULT_GROUP
        timeout: 3000
        maxRetry: 3
        configLongPollTimeout: 30_000
        namespace: ${spring.application.name}
        clusterName: ${spring.application.name}